export const allProjects = [
  {
    title: 'The Digital Forge',
    // Narrative: Focus on "Self-Healing" and "Sandboxing"
    description: 'An autonomous multi-agent coding system that achieved an 85% Pass@1 rate on algorithmic tasks. Features a "Self-Healing" reflection loop where agents execute code in a Dockerized sandbox, capture stderr, and iteratively debug their own errors.',
    featured: true,
    tags: ['Multi-Agent Systems', 'Docker', 'CrewAI', 'CI/CD', 'Python'],
    github: 'https://github.com/MohammedPathariya/TheDigitalForge',
    demo: 'https://thedigitalforge.onrender.com/',
    thumbnail: '/images/digitalforge.png',
  },
  {
    title: 'LearnLoop',
    // Narrative: Focus on "Reliability" and "Concurrency"
    description: 'A fault-tolerant RAG architecture designed for reliability. Engineered with Session-Based FAISS indexes for strict data isolation and a Pydantic-powered validation layer that autonomously corrects 90% of LLM JSON schema hallucinations.',
    featured: true,
    tags: ['RAG', 'Pydantic', 'SQLite WAL', 'Locust', 'React'],
    github: 'https://github.com/MohammedPathariya/LearnLoop-Deployment',
    demo: 'https://learnloop-deployment-frontend.vercel.app/',
    thumbnail: '/images/learnloop.png',
  },
  {
    title: 'AudioGroove',
    // Narrative: Focus on "Scale" and "Research"
    description: 'A comparative research study scaling Deep Learning to 175,000+ MIDI files. Built a distributed Dask ETL pipeline to handle the massive dataset and proved that Bi-Directional LSTMs statistically outperform DCGANs for symbolic music generation.',
    featured: true,
    tags: ['Deep Learning', 'Dask', 'MLflow', 'PyTorch', 'Research'],
    github: 'https://github.com/MohammedPathariya/AudioGroove',
    demo: 'https://audiogroove.vercel.app/',
    thumbnail: '/images/audiogroove2.png',
  },
  {
    title: 'HandSpeak',
    description: 'Built a real-time sign language detection system using MediaPipe and Scikit-Learn, achieving high accuracy without the need for deep learning models.',
    featured: true,
    tags: ['MediaPipe', 'Scikit-Learn', 'Flask', 'OpenCV'],
    github: 'https://github.com/MohammedPathariya/HandSpeak',
    demo: 'https://handspeak-blush.vercel.app/',
    thumbnail: '/images/handspeak2.png',
  },
  {
    title: 'VAYU – Air Quality Forecasting',
    description: 'Forecasted Air Quality Index (AQI) with an LSTM model trained on OpenAQ time series data, managing the full pipeline from data cleaning to evaluation.',
    featured: false,
    tags: ['Time Series', 'LSTM', 'Pandas', 'Scikit-Learn'],
    github: 'https://github.com/MohammedPathariya/LSTM-Air-Quality-Forecasting--VAYU',
    demo: '#',
    thumbnail: '/images/vayu2.png',
  },
  {
    title: 'Automated Snake Game',
    description: 'Trained a self-playing Snake agent using Deep Reinforcement Learning (DRL) in PyTorch, enabling it to learn optimal strategies for maximizing its score.',
    featured: false,
    tags: ['Reinforcement Learning', 'PyTorch', 'Pygame'],
    github: 'https://github.com/MohammedPathariya/Automated-Snake-Game',
    demo: '#',
    thumbnail: '/images/automatedsnakegame2.png',
  },
  {
    title: 'BloomMap',
    description: 'Developed an interactive map of Bloomington’s public facilities with a React/Flask stack, using GeoPandas for geospatial data analysis and filtering.',
    featured: false,
    tags: ['React', 'Flask', 'GeoPandas', 'Docker'],
    github: 'https://github.com/MohammedPathariya/BloomMap',
    demo: '#',
    thumbnail: '/images/bloommap2.png',
  },
  {
    title: 'CodeCrafter',
    description: 'Created a language-agnostic web app to execute Python/R code in isolated Docker containers, rendering static and interactive data visualizations.',
    featured: false,
    tags: ['React', 'Flask', 'Docker', 'Data Viz'],
    github: 'https://github.com/MohammedPathariya/CodeCrafter',
    demo: '#',
    thumbnail: '/images/codecrafter2.png',
  },
  {
    title: 'Content Detection',
    description: 'Built a spam email classifier using LSTM and FNN models with NLP preprocessing for text classification.',
    featured: false,

    tags: ['LSTM', 'NLP', 'TensorFlow'],
    github: 'https://github.com/MohammedPathariya/Content-Detection',
    demo: '#',
    thumbnail: '/images/contentdetection.png',
  },
  {
    title: 'Yudishthir Desktop Assistant',
    description: 'Built a voice-activated desktop assistant in Python with modules for automation, surveillance, and real-time information lookup.',
    featured: false,
    tags: ['Speech Recognition', 'Automation', 'OpenCV'],
    github: 'https://github.com/MohammedPathariya/Desktop-Assistant-Yudhishthar',
    demo: '#',
    thumbnail: '/images/yudhisthir.png',
  },
];